name:    url-shortner
version: "0.0.0"

dependencies:
- base
- yesod-core
- text
- directory
- filepath
- random

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  url-shortner:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - url-shortner
